{
 "title": "Dashboard",
 "time": { "from": "now-1w", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "staging,prod" }
  ]
 },
 "panels": [
  {
   "title": "For Technical and Nontechnical People",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Note",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "The HTTP requests are being originate from the `ap-south-1` AWS region (Mumbai, India). This is because we're testing our own blockchain nodes which are hosted in the `us-east-1` AWS region (Northern Virginia, USA). If we were to host _Observatory_ in the `us-east-1` AWS region too, then the durations would be negligible (such as 20 ms while the others are 1 s) because AWS would internally route the HTTP request for speed. Since we want to simulate durations as our customers will experience them, we're hosting _Observatory_ in a geographical region far away from the one used to host most blockchain nodes (including our own)."
   }
  },
  {
   "title": "Average HTTP Request Durations",
   "type": "stat",
   "description": "The average duration in seconds of HTTP requests made to each blockchain node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    label_replace(\n      http_request_duration_seconds_sum{job=\"observatory\", env=\"$env\"}\n        / http_request_duration_seconds_count{job=\"observatory\", env=\"$env\"},\n      \"env\",\n      \"\",\n      \"env\",\n      \".*\"\n    ),\n    \"instance\",\n    \"\",\n    \"instance\",\n    \".*\"\n  ),\n  \"job\",\n  \"\",\n  \"job\",\n  \".*\"\n)"
    }
   ]
  },
  {
   "title": "Average HTTP Request Durations Over Time",
   "type": "heatmap",
   "description": "The average duration in seconds of HTTP requests made to each blockchain node. It's shown over time so that you can see the reliability during potential traffic spikes throughout the week.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    label_replace(\n      http_request_duration_seconds_sum{job=\"observatory\", env=\"$env\"}\n        / http_request_duration_seconds_count{job=\"observatory\", env=\"$env\"},\n      \"env\",\n      \"\",\n      \"env\",\n      \".*\"\n    ),\n    \"instance\",\n    \"\",\n    \"instance\",\n    \".*\"\n  ),\n  \"job\",\n  \"\",\n  \"job\",\n  \".*\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL Success Rates",
   "type": "timeseries",
   "description": "The success rate percentage for each URL over time. URLs that aren't plotted have a 100% success rate.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n    label_replace(\n        label_replace(\n            (\n                (http_requests_succeeded_total{job=\"observatory\",env=\"$env\"} * 100)\n                /\n                (\n                    http_requests_succeeded_total{job=\"observatory\",env=\"$env\"}\n                    + http_requests_failed_total{job=\"observatory\",env=\"$env\"}\n                )\n            ),\n            \"instance\",\n            \"\",\n            \"instance\",\n            \".*\"\n        ),\n        \"job\",\n        \"\",\n        \"job\",\n        \".*\"\n    ),\n    \"env\",\n    \"\",\n    \"env\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "For Technical People", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Logs (Prod)",
   "type": "logs",
   "description": "Logs from the production environment.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{job=\"observatory\",env=\"prod\"}"
    }
   ]
  },
  {
   "title": "Logs (Staging)",
   "type": "logs",
   "description": "Logs from the staging environment.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{job=\"observatory\",env=\"staging\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "description": "The state of every alert configured for Observatory.",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 43 }
  },
  {
   "title": "Syslog Levels \"Warning\" and \"Error\"",
   "type": "timeseries",
   "description": "The number of logs with Syslog levels \"warning\" and \"error\".",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    count_over_time(\n      {job=\"observatory\", filename=~\".*default.*\"} |~ `\"level\":\"(error|warning)\"`\n      [1m]\n    ),\n    \"filename\",\n    \"\",\n    \"filename\",\n    \".*\"\n  ),\n  \"job\",\n  \"\",\n  \"job\",\n  \".*\"\n)"
    }
   ]
  },
  {
   "title": "Syslog Levels \"Critical\" and \"Alert\"",
   "type": "timeseries",
   "description": "The number of logs with Syslog levels \"critical\" and \"alert\".",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    count_over_time(\n      {job=\"observatory\", filename=~\".*default.*\"} |~ `\"level\":\"(alert|crit)\"`\n      [1m]\n    ),\n    \"filename\",\n    \"\",\n    \"filename\",\n    \".*\"\n  ),\n  \"job\",\n  \"\",\n  \"job\",\n  \".*\"\n)"
    }
   ]
  },
  {
   "title": "Syslog Level \"Emergency\"",
   "type": "timeseries",
   "description": "The number of logs with the Syslog level \"emergency\".",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    count_over_time({job=\"observatory\", filename=~\".*default.*\"} |= `\"level\":\"emerg\"` [1m]),\n    \"filename\",\n    \"\",\n    \"filename\",\n    \".*\"\n  ),\n  \"job\",\n  \"\",\n  \"job\",\n  \".*\"\n)"
    }
   ]
  },
  {
   "title": "Unhandled Exceptions",
   "type": "timeseries",
   "description": "These differ from the errors in the other charts.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    count_over_time({job=\"observatory\",filename=~\".*(rejections|exceptions).*\"} |~ \".*\" [1m]),\n    \"filename\",\n    \"\",\n    \"filename\",\n    \".*\"\n  ),\n  \"job\",\n  \"\",\n  \"job\",\n  \".*\"\n)"
    }
   ]
  }
 ]
}