on:
  push:
    branches: [staging, prod]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: yarn
      - run: yarn
      - run: yarn lint:check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: yarn
      - run: yarn
      - run: yarn test
  tag:
    if: github.ref_name == 'prod'
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
      - name: Set $VERSION
        run: echo "VERSION=$(yarn env | grep npm_package_version | grep -Eo '[0-9.]*')" >> $GITHUB_ENV
      - run: yarn
      - run: zip -r docs.zip docs/index.html docs/openapi.yaml
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v$VERSION docs.zip \
            -t v$VERSION \
            -n "[Changelog](https://github.com/leapwallet/observatory/blob/v$VERSION/docs/CHANGELOG.md)" \
            $([[ $VERSION = 0* ]] && echo '-p')
  deploy:
    # if: github.ref_name == 'migration/gcp'
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
      - name: Login to Artifact Registry
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.ARTIFACT_REGISTRY_KEY }}
      - name: Set Gcloud as credential helper for Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            asia-south1-docker.pkg.dev/leap-393508/observatory/observatory:dummy_branch
            # asia-south1-docker.pkg.dev/leap-393508/observatory/observatory:${{ github.ref_name }}
